import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Hero from "./components/Hero";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          {/* <main>
            <Hero />
          </main>
          <main>
            <Navbar />
          </main> */}
          <main className="flex-grow"> {children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}

// {/* Wrapper div to handle layout */}
// <div className="flex flex-col min-h-screen ">
// {/* Header and Navbar */}

// <main>
//   {!isAccountPage && <Header />}
//   {/* <Header /> */}
// </main>
// <main>
//   {!isAccountPage && <Navbar />}

//   {/* <Navbar />  */}
// </main>
// {/* Main content (fills available space) */}
// <main className="flex-grow">{children}</main>
// {/* Footer at the bottom */}
// {!isAccountPage && <Footer />}
// {/* <Footer /> */}
// </div>
